// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

module.exports = {
  mainSidebar: [
    {
      type: "html",
      value:
        '<a class="navbar__brand" href="/"><div class="navbar__logo"><img src="/img/walletconnect-logo-white.svg#dark-mode-only"  alt="WalletConnect Logo"><img src="/img/walletconnect-logo-black.svg#light-mode-only"  alt="WalletConnect Logo"></div>WalletConnect<span>Specs<span></a>',
      defaultStyle: true,
    },
    {
      type: "category",
      label: "Specs",
      collapsed: true,
      collapsible: true,
      items: [
        "readme",
        {
          type: "category",
          label: "Client APIs",
          items: [
            {
              type: "category",
              label: "Sign API",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/clients/sign",
                },
              ],
            },
            {
              type: "category",
              label: "Auth API",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/clients/auth",
                },
              ],
            },
            {
              type: "category",
              label: "Chat API",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/clients/chat",
                },
              ],
            },
            {
              type: "category",
              label: "Push API",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/clients/push",
                },
              ],
            },
            {
              type: "category",
              label: "Core API",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/clients/core",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Meta-Clients API",
          items: [
            {
              type: "category",
              label: "Web3Inbox",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/meta-clients/web3inbox",
                },
              ],
            },
            {
              type: "category",
              label: "Web3Wallet",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/meta-clients/web3wallet",
                },
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Server APIs",
          items: [
            {
              type: "category",
              label: "Relay Server",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/servers/relay",
                },
              ],
            },
            {
              type: "category",
              label: "Keys Server",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/servers/keys",
                },
              ],
            },
            {
              type: "category",
              label: "Echo Server",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/servers/echo",
                },
              ],
            },
            {
              type: "category",
              label: "Cast Server",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/servers/cast",
                },
              ],
            },
            {
              type: "category",
              label: "History Server",
              items: [
                {
                  type: "autogenerated",
                  dirName: "specs/servers/history",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Blockchain RPC",
      items: [
        {
          type: "autogenerated",
          dirName: "blockchain-rpc",
        },
      ],
    },
    {
      type: "category",
      label: "Glossary",
      items: [
        {
          type: "autogenerated",
          dirName: "glossary",
        },
      ],
    },
  ],
};
